### ISSUE TITLE
Test dependencies are quite old.

### ISSUE THREAD

**Issue by layus** [TikhonJelvis/modular-arithmetic#12]
Tests require old versions of Glob (0.7.*) and doctest. Would it be possible to update that or get rid of them ? It seems that glob is used only in one place, to generate a list of one file ;-).

**Comment by TikhonJelvis** [comment]
Thanks for pointing that out! 

I've had problems with Glob and Nix in the past. In hindsight, I should have removed the dependency back then.

**Comment by TikhonJelvis** [comment]
Okay, I removed the dependency on `Glob` and released [1.2.1.4](http://hackage.haskell.org/package/modular-arithmetic-1.2.1.4) on Hackage.

**Comment by layus** [comment]
Thanks !
