### ISSUE TITLE
Hackage documentation for module missing

### ISSUE THREAD

**Issue by FranklinChen** [TikhonJelvis/modular-arithmetic#18]
https://hackage.haskell.org/package/modular-arithmetic does not have a link for `Data.Modular` documentation as I had expected.

**Comment by TikhonJelvis** [comment]
Thanks for spotting this!

I believe there is a way to manually upload documentation to Hackage. I'll give that a try.

**Comment by TikhonJelvis** [comment]
Okay, should work now: https://hackage.haskell.org/package/modular-arithmetic-2.0.0.0/docs/Data-Modular.html
