### ISSUE TITLE
Instantiate Fractional and use recip instead of inv?

### ISSUE THREAD

**Issue by CarlEdman** [TikhonJelvis/modular-arithmetic#8]
Very nice.  But I think I would make Mod an instance of Fractional and use its recip function instead of inv.  Also Fractional's (/) really has better semantics than div for (/) always yields an exact result, just like (/) does for Rationals and Doubles (up to machine precision), rather than some defined approximation like div (for Integrals).  In that regard Mod division is more like (/) than div.

Also Fractional's fromRational does make sense for Mods in many circumstances.  Note, for example, that fromRational always results in a Mod which has a reciprocal because the Rational is in reduced form and numerator and denominator are hence co-prime.  And in circumstances where this is not a sensible thing to think about, one can just not use fromRational and suffer no harm.

**Comment by TikhonJelvis** [comment]
Hey, this is a great suggest. It totally slipped my radar five years ago; sorry for the really delayed response!

This was brought back to my attention by #14; I think implementing this suggestion (getting rid of the `Integral` instance and replacing it with a `Fractional` instance) is how I'm going to solve that problem.

Thanks for making this suggestion way back when :).

**Comment by TikhonJelvis** [comment]
Okay, this shouldn't be a problem after #15 because we don't have an `Integral` instance any more, so using `^` with a `Mod` as the power won't typecheck any more.

**Comment by TikhonJelvis** [comment]
Implemented in #15. Thanks for the suggestion even though it took me years to do it :).
